# Generated by Django 5.2.1 on 2025-06-25 19:14

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('questions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('times_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='content_hash',
            field=models.CharField(default='default_hash', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT', 'Short Answer')], default=datetime.datetime(2025, 6, 1, 0, 0), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
