# Generated by Django 5.2.1 on 2025-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides_analyzer', '0006_chatbotknowledge_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag for user/admin'),
        ),
    ]
