# Generated by Django 5.2.1 on 2025-07-16 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides_analyzer', '0007_userprofile_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title/name', max_length=255)),
                ('subject', models.CharField(help_text='Subject of the exam', max_length=100)),
                ('year', models.IntegerField(blank=True, help_text='Year of the exam', null=True)),
                ('document_file', models.FileField(help_text='Upload exam document (PDF, DOCX, TXT)', upload_to='exam_documents/')),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text from document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Document',
                'verbose_name_plural': 'Exam Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject being analyzed', max_length=100)),
                ('analysis_data', models.JSONField(default=dict, help_text='Analysis results including trends and predictions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_analyses', to=settings.AUTH_USER_MODEL)),
                ('documents_analyzed', models.ManyToManyField(related_name='analyses', to='slides_analyzer.examdocument')),
            ],
            options={
                'verbose_name': 'Exam Analysis',
                'verbose_name_plural': 'Exam Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Subject/topic of the quiz', max_length=100)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Time taken in minutes')),
                ('questions_data', models.JSONField(default=dict, help_text='Stored quiz questions and answers')),
                ('user_answers', models.JSONField(default=dict, help_text="User's answers")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Session',
                'verbose_name_plural': 'Quiz Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
