# Generated by Django 5.2.1 on 2025-07-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides_analyzer', '0008_examdocument_examanalysis_quizsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag for manual admin use only'),
        ),
    ]
