# Generated by Django 5.2.1 on 2025-07-22 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides_analyzer', '0008_examdocument_examanalysis_quizsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='examanalysis',
            name='subject',
            field=models.CharField(db_index=True, help_text='Subject being analyzed', max_length=100),
        ),
        migrations.AlterField(
            model_name='questioncache',
            name='last_used',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='questioncache',
            name='question_content_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='subject',
            field=models.CharField(blank=True, db_index=True, help_text='Subject/topic of the quiz', max_length=100),
        ),
        migrations.AddIndex(
            model_name='examanalysis',
            index=models.Index(fields=['user', '-created_at'], name='slides_anal_user_id_9bde54_idx'),
        ),
        migrations.AddIndex(
            model_name='examanalysis',
            index=models.Index(fields=['subject', '-created_at'], name='slides_anal_subject_9993cd_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', '-created_at'], name='slides_anal_user_id_b1ee47_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['subject', '-created_at'], name='slides_anal_subject_0bb254_idx'),
        ),
    ]
